[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.11.0"
  NEXT_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.google.com *.googleapis.com *.gstatic.com; img-src 'self' data: blob: https:; connect-src 'self' https://*.google.com https://*.googleapis.com;" 